openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Custom Entities API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Custom Entities
paths:
  /api/custom-entitytypes:
    get:
      description: This end point lists custom Entity Type Definition
      operationId: listCustomEntities
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomEntityWithMetadata'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: List custom Entity Type Definition
      tags:
      - Custom Entities
      x-ibm-ahub-byok: true
    post:
      description: This end point creates a custom entity type
      operationId: createCustomEntities
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomEntityModel'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomEntityWithMetadata'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Create a Custom Entity type
      tags:
      - Custom Entities
      x-ibm-ahub-byok: true
  /api/custom-entitytypes/{id}:
    delete:
      description: This end point deletes a custom Entity type definition
      operationId: deleteCustomEntity
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomEntityModel'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomEntityWithMetadata'
          description: Entity Deleted
      security:
      - ApiKeyAuth:
        - Default
      summary: Delete a Custom Entity Type
      tags:
      - Custom Entities
      x-ibm-ahub-byok: true
    get:
      description: This endpoint gets custom Entity Type by ID
      operationId: getCustomEntity
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomEntityWithMetadata'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get custom Entity Types
      tags:
      - Custom Entities
      x-ibm-ahub-byok: true
    put:
      description: This end points updates the definition of a custom entity type
      operationId: updateCustomEntity
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomEntityModel'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomEntityWithMetadata'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Update a Custom Entity Type
      tags:
      - Custom Entities
      x-ibm-ahub-byok: true
components:
  schemas:
    CustomEntityWithMetadata:
      type: object
      properties:
        created:
          type: integer
          format: int64
        data:
          $ref: '#/components/schemas/CustomEntityModel'
        id:
          type: string
        version:
          type: string
      required:
      - data
      - id
    CustomMetric:
      type: object
      properties:
        aggregation:
          type: string
          description: Aggregation to apply on the metric for every member.
          enum:
          - AVG
          - SUM
        category:
          type: string
          description: Category of the metric in the catalog
        description:
          type: string
          description: Description to be used in the catalog
        formatter:
          type: string
          description: '|

            * NUMBER: Generic number

            * BYTES: Number of bytes

            * KILO_BYTES: Number of kilobytes

            * MEGA_BYTES: Number of megabytes

            * PERCENTAGE: Percentage in scale [0,1]

            * PERCENTAGE_100: Percentage in scale [0,100]

            * PERCENTAGE_NO_CAPPING: Percentage in scale [0,1] but value could exceed 1 for example when metric is aggregated

            * PERCENTAGE_100_NO_CAPPING: Percentage in scale [0,100] but value could exceed 100 for example when metric is aggregated

            * LATENCY: Time in milliseconds, with value of 0 should not be considered a a strict 0, but considered as < 1ms

            * NANOS: Time in nanoseconds

            * MILLIS: Time in milliseconds

            * MICROS: Time in microseconds

            * SECONDS: Time in seconds

            * RATE: Number of occurrences per second

            * BYTE_RATE: Number of bytes per second

            * UNDEFINED: Metric value unit is not known

            '
          enum:
          - NUMBER
          - BYTES
          - KILO_BYTES
          - MEGA_BYTES
          - PERCENTAGE
          - PERCENTAGE_100
          - PERCENTAGE_NO_CAPPING
          - PERCENTAGE_100_NO_CAPPING
          - LATENCY
          - NANOS
          - MILLIS
          - MICROS
          - SECONDS
          - RATE
          - BYTE_RATE
          - UNDEFINED
        label:
          type: string
          description: Label to be used in the catalog
        name:
          type: string
          description: Name of the metric
        section:
          type: string
          description: Section of the metric in the catalog
          enum:
          - ACE
          - ALICLOUD
          - AWS
          - AZURE
          - CASSANDRA
          - CLOUD_FOUNDRY
          - CLR
          - COCKROACH
          - CONSUL
          - CONTAINER
          - COUCHBASE
          - DFQ
          - ELASTICSEARCH
          - GCP
          - HADOOP_YARN
          - HAZELCAST
          - IBM_CLOUD
          - IBM_DATAPOWER
          - IBM_I_SERIES
          - IBM_MQ
          - IBM_MQMFT
          - IBM_OPENSTACK
          - KAFKA_CONNECT
          - KUBERNETES
          - MONGO_DB
          - OTHERS
          - REDIS
          - SAP
          - SELF_MONITORING
          - SOLR
          - SPARK
          - TIBCOBW
          - TUXEDO
          - VSHPERE
          - WEBSPHERE
          - CUSTOM_ENTITY
        source:
          type: string
          description: Name of the source metric
        type:
          type: string
          description: Type of entity for the source metric
    CustomDashboard:
      type: object
      properties:
        accessRules:
          type: array
          items:
            $ref: '#/components/schemas/AccessRule'
          maxItems: 64
          minItems: 1
        id:
          type: string
        title:
          type: string
        widgets:
          type: array
          items:
            $ref: '#/components/schemas/Widget'
          maxItems: 128
          minItems: 0
          uniqueItems: true
      required:
      - accessRules
      - id
      - title
      - widgets
    CustomDependency:
      type: object
      properties:
        direction:
          type: string
          enum:
          - outgoing
          - incoming
          maxLength: 64
          minLength: 1
        entityType:
          type: string
          description: If entityType is set, the dependency will be added to the plugin for that entity type. Otherwise, the dependency will be applied to the custom entity itself.
          maxLength: 64
          minLength: 0
        identifiers:
          type: array
          description: Will take the identifiers values for building the key of the dependency.
          items:
            type: string
            description: Will take the identifiers values for building the key of the dependency.
          maxItems: 512
          minItems: 0
          uniqueItems: true
        name:
          type: string
          maxLength: 256
          minLength: 1
        separator:
          type: string
          description: Separator between identifiers for building the key of the dependency.
        type:
          type: string
          enum:
          - in
          - is
          - to
          - of
          - connected
          - describes
          - of20
          - to20
          - dummy
          - parent
          maxLength: 8
          minLength: 1
    Widget:
      type: object
      properties:
        config:
          type: object
        height:
          type: integer
          format: int32
          minimum: 1
        id:
          type: string
          maxLength: 64
          minLength: 0
        title:
          type: string
        type:
          type: string
        width:
          type: integer
          format: int32
          maximum: 12
          minimum: 1
        x:
          type: integer
          format: int32
          maximum: 11
          minimum: 0
        y:
          type: integer
          format: int32
          minimum: 0
      required:
      - config
      - id
      - type
    TagFilterExpressionElement:
      type: object
      description: Boolean expression of tag filters to define the scope of relevant calls.
      discriminator:
        mapping:
          EXPRESSION: '#/components/schemas/TagFilterExpression'
          TAG_FILTER: '#/components/schemas/TagFilter'
        propertyName: type
      properties:
        type:
          type: string
      required:
      - type
    AccessRule:
      type: object
      properties:
        accessType:
          type: string
          description: "Specifies the type of access permitted. \n\n`READ`: Only viewing Application Perspective is allowed. \n\n`READ_WRITE`: Both viewing and modifying Application Perspective are permitted. \n\n"
          enum:
          - READ
          - READ_WRITE
        relatedId:
          type: string
          description: "An identifier that connects the access rule to a specific entity.\nFor example, if the `relationType` is `USER`, the corresponding `relatedId` would be a user id. \n\n**Note**: when `relationType` is `GLOBAL`, `relatedId` is `null`.\n"
          maxLength: 64
          minLength: 0
        relationType:
          type: string
          description: "Defines the type of relationship or subject to which the access rule applies. \n\n`USER`: Access is granted to an individual user. \n\n`API_TOKEN`: Access is granted to a specific API token. \n\n`ROLE`: Access is granted based on a user role, applying to any user with that role. \n\n`TEAM`: Access is granted to a team, likely applying to all team members. \n\n`GLOBAL`: Access is granted to every user or service.\n"
          enum:
          - USER
          - API_TOKEN
          - ROLE
          - TEAM
          - GLOBAL
      required:
      - accessType
      - relationType
    CustomEntityModel:
      type: object
      properties:
        dashboards:
          type: array
          items:
            $ref: '#/components/schemas/CustomDashboard'
          uniqueItems: true
        dependencies:
          type: array
          items:
            $ref: '#/components/schemas/CustomDependency'
          uniqueItems: true
        identifiers:
          type: array
          items:
            type: string
        label:
          type: string
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/CustomMetric'
          uniqueItems: true
        tagFilterExpression:
          $ref: '#/components/schemas/TagFilterExpressionElement'
      required:
      - identifiers
      - label
      - tagFilterExpression
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
