openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Apdex Report API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Apdex Report
paths:
  /api/apdex/report/{apdexId}:
    get:
      description: Generate Apdex Report for a specified Apdex ID.
      operationId: getApdexReport
      parameters:
      - description: Apdex Configuration ID
        example: nCtEoR6NSPqG61QkIkwwCw
        in: path
        name: apdexId
        required: true
        schema:
          type: string
      - description: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        example: 1706713140000
        in: query
        name: from
        required: true
        schema:
          type: integer
          format: int64
      - description: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        example: 1706813100000
        in: query
        name: to
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          content:
            application/json:
              example:
                apdexId: nCtEoR6NSPqG61QkIkwwCw
                from: 1706713140000
                to: 1706813100000
                apdexScore:
                - - 1706713140000
                  - 0.5
                - - 1706779500000
                  - 0.5
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApdexReport'
          description: OK
        '404':
          content:
            application/json:
              example:
                errors:
                - There is no Apdex configuration for the given ID.
              schema:
                type: array
                items:
                  type: string
          description: No Apdex configuration for the given ID
      security:
      - ApiKeyAuth:
        - Default
      summary: Generate Apdex report
      tags:
      - Apdex Report
      x-ibm-ahub-byok: true
components:
  schemas:
    ApdexReport:
      type: object
      properties:
        apdexId:
          type: string
          description: Apdex Configuration ID
        apdexScore:
          type: array
          description: Apdex Score in different timestamps from starting to the ending point
          items:
            type: array
            description: Apdex Score in different timestamps from starting to the ending point
            items:
              type: number
              description: Apdex Score in different timestamps from starting to the ending point
        from:
          type: integer
          format: int64
          description: Starting point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
        to:
          type: integer
          format: int64
          description: Ending point for the data retrieval, specified as 13 digit Unix Timestamp milliseconds
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
