openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Host Agent API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Host Agent
  description: Endpoints of this group can be used to list and configure host agents.
paths:
  /api/host-agent:
    get:
      operationId: searchHostAgents
      parameters:
      - in: query
        name: query
        schema:
          type: string
      - in: query
        name: to
        schema:
          type: integer
          format: int64
      - in: query
        name: windowSize
        schema:
          type: integer
          format: int64
      - in: query
        name: size
        schema:
          type: integer
          format: int32
      - in: query
        name: offline
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              example: "  {\n    \"items\": [\n        {\n            \"snapshotId\": \"iRsnjcH9cls2rlx3wm8ENPapljk\",\n            \"plugin\": \"instanaAgent\",\n            \"from\": 1706712590000,\n            \"to\": null,\n            \"tags\": [],\n            \"label\": \"Instana Agent @ ip-10-255-207-205\",\n            \"host\": \"EC2-i-0a8be85269f7e2b92\"\n        },\n    ]\n}\n"
              schema:
                $ref: '#/components/schemas/SnapshotResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Query host agent snapshots
      tags:
      - Host Agent
      x-ibm-ahub-byok: true
  /api/host-agent/configuration:
    post:
      operationId: updateConfigurationByQuery
      parameters:
      - in: query
        name: query
        schema:
          type: string
      - in: query
        name: to
        schema:
          type: integer
          format: int64
      - in: query
        name: windowSize
        schema:
          type: integer
          format: int64
      - in: query
        name: size
        schema:
          type: integer
          format: int32
      - in: query
        name: offline
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentConfigurationUpdate'
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - Default
      - ApiKeyAuth:
        - canConfigureAgents
      summary: Update agent configuration by query
      tags:
      - Host Agent
      x-ibm-ahub-byok: true
      description: This endpoint can be used to initialize or change configuration management settings for all agents selected by the given Dynamic Focus Query.
  /api/host-agent/{hostId}/clr-logs:
    get:
      operationId: getAgentClrLogs
      parameters:
      - in: path
        name: hostId
        required: true
        schema:
          type: string
      - in: query
        name: download
        schema:
          type: boolean
      responses:
        default:
          content:
            application/octet-stream: {}
          description: default response
      security:
      - ApiKeyAuth:
        - Default
      - ApiKeyAuth:
        - canConfigureAgents
      summary: Agent CLR download logs
      tags:
      - Host Agent
      x-ibm-ahub-byok: true
  /api/host-agent/{hostId}/configuration:
    post:
      operationId: updateConfigurationByHost
      parameters:
      - in: path
        name: hostId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentConfigurationUpdate'
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - Default
      - ApiKeyAuth:
        - canConfigureAgents
      summary: Update agent configuration by host
      tags:
      - Host Agent
      x-ibm-ahub-byok: true
      description: This endpoint can be used to initialize or change configuration management settings for a specific host agent.
  /api/host-agent/{hostId}/logs:
    get:
      operationId: getAgentLogs
      parameters:
      - in: path
        name: hostId
        required: true
        schema:
          type: string
      - in: query
        name: download
        schema:
          type: boolean
      - in: query
        name: file
        required: true
        schema:
          type: array
          items:
            type: string
          uniqueItems: true
      responses:
        default:
          content:
            application/octet-stream: {}
          description: default response
      security:
      - ApiKeyAuth:
        - Default
      - ApiKeyAuth:
        - canConfigureAgents
      summary: Agent download logs
      tags:
      - Host Agent
      x-ibm-ahub-byok: true
  /api/host-agent/{hostId}/support-info:
    get:
      operationId: getAgentSupportInformation
      parameters:
      - in: path
        name: hostId
        required: true
        schema:
          type: string
      - in: query
        name: supportInfoId
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/octet-stream: {}
          description: default response
      security:
      - ApiKeyAuth:
        - Default
      - ApiKeyAuth:
        - canConfigureAgents
      summary: Agent download support information
      tags:
      - Host Agent
      x-ibm-ahub-byok: true
  /api/host-agent/{hostId}/update:
    post:
      operationId: updateAgent
      parameters:
      - in: path
        name: hostId
        required: true
        schema:
          type: string
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - Default
      - ApiKeyAuth:
        - canConfigureAgents
      summary: Agent update
      tags:
      - Host Agent
      x-ibm-ahub-byok: true
  /api/host-agent/{id}:
    get:
      operationId: getAgentSnapshot
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      - in: query
        name: to
        schema:
          type: integer
          format: int64
      - in: query
        name: windowSize
        schema:
          type: integer
          format: int64
      responses:
        '200':
          content:
            application/json:
              example: "  {\n    \"snapshotId\": \"snapshot id\",\n    \"plugin\": \"instanaAgent\",\n    \"from\": 1706791431000,\n    \"tags\": [],\n    \"label\": \"Instana Agent @ ip-10-255-207-205\",\n    \"entityId\": {\n        \"host\": \"EC2-i-0a8be85269f7e2b92\",\n        \"pluginId\": \"plugin id\",\n        \"steadyId\": \"self\"\n    },\n    \"data\": {\n        \"memory.nativeTotal\": 134217728,\n        \"capabilities\": [\n            \"gitops\",\n            \"logdownload\",\n            \"agentprofiler\",\n            \"agentSupportInfo\",\n            {\n                \"java-trace-commands\": [\n                    \"get-agent-statistics\",\n                    \"get-loader-statistics\",\n                    \"get-tracer-statistics\",\n                    \"get-instrumentation-install-messages\",\n                    \"get-instrumentation-install-errors\",\n                    \"get-instrumentation-runtime-errors\",\n                    \"get-instrumented-classes\",\n                    \"get-raw-matchers\",\n                    \"get-weak-concurrent-maps\",\n                    \"log-reset\",\n                    \"log-trace-context\",\n                    \"log-rejected\",\n                    \"start-debug-tracer\",\n                    \"stop-debug-tracer\"\n                ]\n            },\n            \"log4j-safe-lib\"\n        ],\n        \"origin\": \"public_docker\",\n        \"startedAt\": 1705917107361,\n        \"memory.total\": 181805056,\n        \"pid\": \"29001\",\n        \"mode\": 2,\n        \"hostname\": \"ip-10-255-207-205\",\n        \"java\": {\n            \"vmversion\": \"25.392-b08\",\n            \"version\": \"1.8.0_392\",\n            \"vmname\": \"vm name\",\n            \"vmvendor\": \"vendor name\"\n        },\n        \"git\": {\n            \"present\": true,\n            \"initialized\": false\n        },\n        \"hasCpuLoad\": true,\n        \"updateMode\": \"Auto\",\n        \"log.counts.byMessage\": {\n            \"?:?\": \"WARN ? \"Can no longer query container metrics for k8s.io: 8ac777f1ca6231299050ee5482ecac6c1747b2545b3b1d890f69d0a849b3adb4 ... requesting sensor shutdown\"\"\n        },\n        \"loglevel\": \"INFO\",\n        \"agentVersion\": \"Latest\",\n        \"metrics\": true,\n        \"boot\": \"1.2.30\",\n        \"pids\": [\n            \"14096\",\n            \"19502\",\n            \"2001\",\n            \"29812\",\n            \"981\",\n            \"28411\",\n            \"29522\",\n            \"1267\",\n            \"2475\",\n            \"27182\"\n        ],\n        \"user\": \"root\",\n        \"logAsRate\": true\n    }\n}\n"
              schema:
                $ref: '#/components/schemas/SnapshotItem'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get host agent snapshot details
      tags:
      - Host Agent
      x-ibm-ahub-byok: true
components:
  schemas:
    SnapshotItem:
      type: object
      description: Detail information for requested snapshots.
      properties:
        data:
          type: object
          additionalProperties:
            type: object
        from:
          type: integer
          format: int64
          description: Start of timeframe expressed as the Unix epoch time in milliseconds
        host:
          type: string
          description: Host name
        label:
          type: string
          description: Friendly label for the entity
        plugin:
          type: string
          description: Plugin name
          example: host
        snapshotId:
          type: string
          description: Snapshot ID
        tags:
          type: array
          description: Tags which can be used to search for this entity
          items:
            type: string
            description: Tags which can be used to search for this entity
        to:
          type: integer
          format: int64
          description: End of timeframe expressed as the Unix epoch time in milliseconds
    SnapshotResult:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/SnapshotItem'
    AgentConfigurationUpdate:
      type: object
      properties:
        remoteBranch:
          type: string
          maxLength: 256
          minLength: 0
        remoteName:
          type: string
          maxLength: 256
          minLength: 0
        remoteUri:
          type: string
          maxLength: 65536
          minLength: 0
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
