openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Authentication API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Authentication
paths:
  /api/settings/authentication/googleSSO:
    delete:
      description: Delete the corresponding tenants Google SSO configuration.
      operationId: deleteGoogleSSOConfig
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Delete Google SSO configuration
      tags:
      - Authentication
      x-ibm-ahub-byok: true
  /api/settings/authentication/ldap:
    delete:
      description: Delete the corresponding tenants LDAP configuration.
      operationId: deleteLdapConfig
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Delete LDAP configuration
      tags:
      - Authentication
      x-ibm-ahub-byok: true
  /api/settings/authentication/oidc:
    delete:
      description: Delete the corresponding tenants OIDC configuration.
      operationId: deleteOidcConfig
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Delete OIDC configuration
      tags:
      - Authentication
      x-ibm-ahub-byok: true
  /api/settings/authentication/saml:
    delete:
      description: Delete the corresponding tenants SAML configuration.
      operationId: deleteSamlConfig
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureAuthenticationMethods
      summary: Delete SAML configuration
      tags:
      - Authentication
      x-ibm-ahub-byok: true
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
