openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation SLI Report API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: SLI Report
paths:
  /api/sli/report/{sliId}:
    get:
      operationId: getSli
      parameters:
      - description: ID of the Service Level Indicator (SLI)
        example: nCtEoR6NSPqG61QkIkwwCw
        in: path
        name: sliId
        required: true
        schema:
          type: string
      - description: Target SLO
        example: 0.99
        in: query
        name: slo
        required: true
        schema:
          type: number
          format: double
      - description: From Timestamp in milliseconds (13-digit)
        example: 1706713140000
        in: query
        name: from
        required: true
        schema:
          type: integer
          format: int64
      - description: To Timestamp in milliseconds (13-digit)
        example: 1706713140000
        in: query
        name: to
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          content:
            application/json:
              example:
                sli: 0.008228916434859497
                slo: 0.1
                totalErrorBudget: 10236633
                errorBudgetRemaining: -1043808
                fromTimestamp: 1707771600000
                toTimestamp: 1707858000000
                violationDistribution: null
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SliReport'
          description: OK
        '404':
          content:
            application/json:
              example:
                errors:
                - There is no SLI configuration for the given ID or the report hasn't been generated yet.
              schema:
                type: array
                items:
                  type: string
          description: There is no SLI configuration for the given ID or the report hasn't been generated yet.
      security:
      - ApiKeyAuth:
        - Default
      summary: 'Generate SLI report (Limitation: the Classic Edition API report can be…'
      tags:
      - SLI Report
      x-ibm-ahub-byok: true
components:
  schemas:
    SliReport:
      type: object
      properties:
        errorBudgetRemaining:
          type: integer
          format: int64
          description: This is the error budget remaining compared to the total error budget
        fromTimestamp:
          type: integer
          format: int64
          description: from timestamp in milliseconds (13-digit)
        sli:
          type: number
          format: double
          description: 'Service Level Indicator: This indicates the actual performance measure of the service'
        slo:
          type: number
          format: double
          description: 'Service Level Objective: This is the target value that should be met by the SLI'
        toTimestamp:
          type: integer
          format: int64
          description: to timestamp in milliseconds (13-digit)
        totalErrorBudget:
          type: integer
          format: int64
          description: This is the total error budget available
        violationDistribution:
          type: object
          additionalProperties:
            type: integer
            format: int32
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
