openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Application Resources API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Application Resources
  description: The API endpoints of this group provides insights into resources created and discovered.
paths:
  /api/application-monitoring/applications:
    get:
      description: 'Use this API endpoint if one wants to retrieve a list of Application Perspectives.

        A use case could be to view the application id of an Application Perspective.


        For more information on Application Resources please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Applications#application-resources.'
      operationId: getApplications
      parameters:
      - description: Name of application
        in: query
        name: nameFilter
        schema:
          type: string
      - description: Size of time window in milliseconds
        in: query
        name: windowSize
        schema:
          type: integer
          format: int64
      - description: Timestamp since Unix Epoch in milliseconds of the end of the time window
        in: query
        name: to
        schema:
          type: integer
          format: int64
      - description: Page number from results
        in: query
        name: page
        schema:
          type: integer
          format: int32
      - description: Number of items per page
        in: query
        name: pageSize
        schema:
          type: integer
          format: int32
      - description: 'Filter for application scope, i.e: INBOUND or ALL'
        in: query
        name: applicationBoundaryScope
        schema:
          type: string
          enum:
          - ALL
          - INBOUND
      responses:
        '200':
          content:
            application/json:
              example:
                items:
                - boundaryScope: INBOUND
                  entityType: APPLICATION
                  id: e8krH1wNRV6daAo-NEmG8g
                  label: Robot Shop
                page: 1
                pageSize: 1
                totalHits: 1
              schema:
                $ref: '#/components/schemas/ApplicationResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get applications
      tags:
      - Application Resources
      x-ibm-ahub-byok: true
  /api/application-monitoring/applications;id=<appId>/services:
    get:
      description: 'Use this API endpoint if one wants to retrieve a list of services in an Application Perspective.

        A use case could be to retrieve all service ids present in an Application Perspective.


        For more information on Application Resources please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Applications#application-resources.'
      operationId: getApplicationServices
      parameters:
      - description: Name of service (partial match allowed)
        in: query
        name: nameFilter
        schema:
          type: string
      - description: Size of time window in milliseconds
        in: query
        name: windowSize
        schema:
          type: integer
          format: int64
      - description: Timestamp since Unix Epoch in milliseconds of the end of the time window
        in: query
        name: to
        schema:
          type: integer
          format: int64
      - description: Page number from results
        in: query
        name: page
        schema:
          type: integer
          format: int32
      - description: Number of items per page
        in: query
        name: pageSize
        schema:
          type: integer
          format: int32
      - description: 'Filter for application scope, i.e: INBOUND or ALL'
        in: query
        name: applicationBoundaryScope
        schema:
          type: string
          enum:
          - ALL
          - INBOUND
      - description: Include snapshot ids in the results
        in: query
        name: includeSnapshotIds
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              example:
                items:
                - entityType: SERVICE
                  id: 79f1430f4a42a707a97621ca00617e40bd51c31d
                  label: www.paypal.com
                  snapshotIds:
                  - CywiRxmGIwtQIKezVs-XMcTX2xg
                  technologies:
                  - kafkaCluster
                  types:
                  - MESSAGING
                page: 1
                pageSize: 1
                totalHits: 1
              schema:
                $ref: '#/components/schemas/ServiceResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get applications/services
      tags:
      - Application Resources
      x-ibm-ahub-byok: true
  /api/application-monitoring/applications/services/endpoints:
    get:
      description: 'Use this API endpoint if one wants to retrieve a list of Endpoints.

        A use case could be to view the endpoint id of an Endpoint.


        For more information on Application Resources please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Applications#application-resources.'
      operationId: getApplicationEndpoints
      parameters:
      - description: Name of service
        in: query
        name: nameFilter
        schema:
          type: string
      - description: Type of Endpoint
        in: query
        name: types
        schema:
          type: array
          items:
            type: string
          uniqueItems: true
      - description: List of technologies
        in: query
        name: technologies
        schema:
          type: array
          items:
            type: string
          uniqueItems: true
      - description: Size of time window in milliseconds
        in: query
        name: windowSize
        schema:
          type: integer
          format: int64
      - description: Timestamp since Unix Epoch in milliseconds of the end of the time window
        in: query
        name: to
        schema:
          type: integer
          format: int64
      - description: Page number from results
        in: query
        name: page
        schema:
          type: integer
          format: int32
      - description: Number of items per page
        in: query
        name: pageSize
        schema:
          type: integer
          format: int32
      - description: 'Filter for application scope, i.e: INBOUND or ALL'
        in: query
        name: applicationBoundaryScope
        schema:
          type: string
          enum:
          - ALL
          - INBOUND
      responses:
        '200':
          content:
            application/json:
              example:
                items:
                - entityType: ENDPOINT
                  id: IWeMKSzcvJHijAQoaA-luyHriDQ
                  label: websites
                  serviceId: a25c02069636022456e6139ebfe4f4bfec23ae31
                  synthetic: false
                  syntheticType: NON_SYNTHETIC
                  technologies:
                  - postgreSqlDatabase
                  type: DATABASE
                page: 1
                pageSize: 1
                totalHits: 1
              schema:
                $ref: '#/components/schemas/EndpointResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get endpoints
      tags:
      - Application Resources
      x-ibm-ahub-byok: true
  /api/application-monitoring/services:
    get:
      description: 'Use this API endpoint if one wants to retrieve a list of Services.

        A use case could be to view the service id of a Service.


        For more information on Application Resources please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Applications#application-resources.'
      operationId: getServices
      parameters:
      - description: Name of service
        in: query
        name: nameFilter
        schema:
          type: string
      - description: Size of time window in milliseconds
        in: query
        name: windowSize
        schema:
          type: integer
          format: int64
      - description: Timestamp since Unix Epoch in milliseconds of the end of the time window
        in: query
        name: to
        schema:
          type: integer
          format: int64
      - description: Page number from results
        in: query
        name: page
        schema:
          type: integer
          format: int32
      - description: Number of items per page
        in: query
        name: pageSize
        schema:
          type: integer
          format: int32
      - description: Include snapshot ids in the results
        in: query
        name: includeSnapshotIds
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              example:
                items:
                - entityType: SERVICE
                  id: 79f1430f4a42a707a97621ca00617e40bd51c31d
                  label: Robot Shop
                  snapshotIds:
                  - CywiRxmGIwtQIKezVs-XMcTX2xg
                  technologies:
                  - kafkaCluster
                  types:
                  - MESSAGING
                page: 1
                pageSize: 1
                totalHits: 1
              schema:
                $ref: '#/components/schemas/ServiceResult'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Get services
      tags:
      - Application Resources
      x-ibm-ahub-byok: true
components:
  schemas:
    ApplicationResult:
      type: object
      properties:
        items:
          type: array
          description: Returns a list of Application Perspectives.
          items:
            $ref: '#/components/schemas/Application'
        page:
          type: integer
          format: int32
          description: Page number you want to retrieve in a request / retrieved in a response.
        pageSize:
          type: integer
          format: int32
          description: number of elements retrieved in a single query.
        totalHits:
          type: integer
          format: int32
          description: 'The number of results returned. For eg: If `items` has 5 elements, `totalhits` will be 5'
    Application:
      type: object
      description: Returns a list of Application Perspectives.
      properties:
        boundaryScope:
          type: string
          description: Here, `ALL` Application Boundary Scope is considered.
        entityType:
          type: string
          description: Since, this is an Application Perspective, it will be of type `APPLICATION`.
          enum:
          - APPLICATION
          - SERVICE
          - ENDPOINT
        id:
          type: string
          description: 'Unique ID of the Application Perspective. Eg: `Av62RoIKQv-A3n6DbMQh9g`.'
        label:
          type: string
          description: 'Name of the Application Perspective. Eg: `app1`.'
      required:
      - boundaryScope
      - id
      - label
    Endpoint:
      type: object
      properties:
        entityType:
          type: string
          description: Since, this is a Endpoint, it will be of type `ENDPOINT`.
          enum:
          - APPLICATION
          - SERVICE
          - ENDPOINT
        id:
          type: string
          description: 'Unique ID of the Endpoint. Eg: `NCRq5oYnan5x-PkdTPQwLLUdu5M`.'
        isSynthetic:
          type: boolean
          writeOnly: true
        label:
          type: string
          description: 'Name of the Endpoint. Eg: `GET /api/fetch`.'
        serviceId:
          type: string
          description: The serviceId this endpoint belongs to.
        synthetic:
          type: boolean
        syntheticType:
          type: string
          enum:
          - NON_SYNTHETIC
          - SYNTHETIC
          - MIXED
        technologies:
          type: array
          description: 'List of technologies: `Eg:["springbootApplicationContainer"]`'
          items:
            type: string
            description: 'List of technologies: `Eg:["springbootApplicationContainer"]`'
          uniqueItems: true
        type:
          type: string
          description: The type of the Endpoint.
          enum:
          - UNDEFINED
          - RPC
          - EVENT
          - GRAPHQL
          - BATCH
          - SHELL
          - HTTP
          - SDK
          - OPENTELEMETRY
          - INTERNAL
          - DATABASE
          - MESSAGING
          - PAGE
          - PAGE_RESOURCE
      required:
      - id
      - label
      - serviceId
      - technologies
      - type
    EndpointResult:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Endpoint'
        page:
          type: integer
          format: int32
          description: Page number you want to retrieve in a request / retrieved in a response.
        pageSize:
          type: integer
          format: int32
          description: number of elements retrieved in a single query.
        totalHits:
          type: integer
          format: int32
          description: 'The number of results returned. For eg: If `items` has 5 elements, `totalhits` will be 5'
    Service:
      type: object
      properties:
        entityType:
          type: string
          description: Since, this is a Service, it will be of type `SERVICE`.
          enum:
          - APPLICATION
          - SERVICE
          - ENDPOINT
        id:
          type: string
          description: 'Unique ID of the Service. Eg: `3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.'
        label:
          type: string
          description: 'Name of the Service. Eg: `payment`.'
        snapshotIds:
          type: array
          description: A unique identifier the metrics are assigned to.
          items:
            type: string
            description: A unique identifier the metrics are assigned to.
          uniqueItems: true
        technologies:
          type: array
          description: 'List of technologies: `Eg:["springbootApplicationContainer"]`'
          items:
            type: string
            description: 'List of technologies: `Eg:["springbootApplicationContainer"]`'
          uniqueItems: true
        types:
          type: array
          description: 'Shows types of Endpoints a Service can consist of. It may be one or more. Eg: `HTTP` `OPENTELEMETRY` can be in 1 Service.'
          items:
            type: string
            description: 'Shows types of Endpoints a Service can consist of. It may be one or more. Eg: `HTTP` `OPENTELEMETRY` can be in 1 Service.'
            enum:
            - UNDEFINED
            - RPC
            - EVENT
            - GRAPHQL
            - BATCH
            - SHELL
            - HTTP
            - SDK
            - OPENTELEMETRY
            - INTERNAL
            - DATABASE
            - MESSAGING
            - PAGE
            - PAGE_RESOURCE
          uniqueItems: true
      required:
      - id
      - label
      - snapshotIds
      - technologies
      - types
    ServiceResult:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Service'
        page:
          type: integer
          format: int32
          description: Page number you want to retrieve in a request / retrieved in a response.
        pageSize:
          type: integer
          format: int32
          description: number of elements retrieved in a single query.
        totalHits:
          type: integer
          format: int32
          description: 'The number of results returned. For eg: If `items` has 5 elements, `totalhits` will be 5'
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
