openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Synthetic Calls API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Synthetic Calls
  description: The API endpoints of this group can fetch, update and delete the synthetic endpoint configuration rules.
paths:
  /api/settings/synthetic-calls:
    delete:
      description: 'Use this API endpoint if one wants to delete all custom synthetic call configurations.

        This endpoint requires `CanConfigureServiceMapping` permission.

        One can use `Create or update an API token` endpoint to update the permission by setting `canConfigureServiceMapping` to `true`.

        If one wants to enable the permission from Instana UI, go to Settings -> Security & Access -> Access Control -> API Token.

        There one can update the existing token or create a new token and set `Customize service rules and endpoint mapping` to `true`.


        For more information on Synthetic Calls please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#synthetic-calls.'
      operationId: deleteSyntheticCall
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - ConfigureServiceMapping
      summary: Delete synthetic call configurations
      tags:
      - Synthetic Calls
      x-ibm-ahub-byok: true
    get:
      description: 'Use this API endpoint if one wants to get all custom synthetic call configurations.

        This endpoint requires `CanConfigureServiceMapping` permission.

        One can use `Create or update an API token` endpoint to update the permission by setting `canConfigureServiceMapping` to `true`.

        If one wants to enable the permission from Instana UI, go to Settings -> Security & Access -> Access Control -> API Token.

        There one can update the existing token or create a new token and set `Customize service rules and endpoint mapping` to `true`.


        For more information on Synthetic Calls please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#synthetic-calls.'
      operationId: getSyntheticCalls
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyntheticCallWithDefaultsConfig'
          description: OK
      security:
      - ApiKeyAuth:
        - ConfigureServiceMapping
      summary: Synthetic call configurations
      tags:
      - Synthetic Calls
      x-ibm-ahub-byok: true
    put:
      description: 'Use this API endpoint if one wants to get all custom synthetic call configurations.

        This endpoint requires `CanConfigureServiceMapping` permission.

        One can use `Create or update an API token` endpoint to update the permission by setting `canConfigureServiceMapping` to `true`.

        If one wants to enable the permission from Instana UI, go to Settings -> Security & Access -> Access Control -> API Token.

        There one can update the existing token or create a new token and set `Customize service rules and endpoint mapping` to `true`.


        For more information on Synthetic Calls please access the https://developer.ibm.com/apis/catalog/instana--instana-rest-api/Settings#synthetic-calls.'
      operationId: updateSyntheticCall
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SyntheticCallConfig'
        required: true
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized access - requires user authentication.
        '403':
          description: Insufficient permissions.
      security:
      - ApiKeyAuth:
        - ConfigureServiceMapping
      summary: Update synthetic call configurations
      tags:
      - Synthetic Calls
      x-ibm-ahub-byok: true
components:
  schemas:
    MatchExpressionDTO:
      type: object
      description: ' Specify the expression to match, For example, `endpoint.name contains health`.'
      discriminator:
        mapping:
          BINARY_OP: '#/components/schemas/BinaryOperatorDTO'
          LEAF: '#/components/schemas/TagMatcherDTO'
        propertyName: type
      properties:
        type:
          type: string
      required:
      - type
    SyntheticCallConfig:
      type: object
      properties:
        customRules:
          type: array
          description: The list of custom rules for synthetic endpoints defined by the user.
          items:
            $ref: '#/components/schemas/SyntheticCallRule'
          maxItems: 500
          minItems: 0
        defaultRulesEnabled:
          type: boolean
          description: A flag to enable/disable the default synthetic endpoint configurations defined by Instana.
      required:
      - customRules
    SyntheticCallWithDefaultsConfig:
      type: object
      properties:
        customRules:
          type: array
          description: The list of custom rules for synthetic endpoints defined by the user.
          items:
            $ref: '#/components/schemas/SyntheticCallRule'
          maxItems: 500
          minItems: 0
        defaultRules:
          type: array
          items:
            $ref: '#/components/schemas/SyntheticCallRule'
        defaultRulesEnabled:
          type: boolean
          description: A flag to enable/disable the default synthetic endpoint configurations defined by Instana.
      required:
      - customRules
      - defaultRules
    SyntheticCallRule:
      type: object
      description: The list of custom rules for synthetic endpoints defined by the user.
      properties:
        description:
          type: string
          description: A description of the custom rule. For example, one can mention the reason behind having the custom rule.
          maxLength: 2048
          minLength: 0
        enabled:
          type: boolean
          description: A flag to enable/disable the custom synthetic endpoint configurations defined by the user.
        matchSpecification:
          $ref: '#/components/schemas/MatchExpressionDTO'
        name:
          type: string
          description: The name of the custom rule for Synthetic endpoints.
          maxLength: 128
          minLength: 1
      required:
      - matchSpecification
      - name
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
