openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Audit Log API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Audit Log
paths:
  /api/settings/accesslog:
    get:
      description: Retrieve all access logs using defined query.
      operationId: getAccessLogs
      parameters:
      - description: The offset within the result set
        example: 0
        in: query
        name: offset
        schema:
          type: integer
          format: int32
      - description: The query to filter the results
        example: username@example
        in: query
        name: query
        schema:
          type: string
      - description: The size of returned page
        example: 10
        in: query
        name: pageSize
        schema:
          type: integer
          format: int32
      responses:
        '200':
          content:
            application/json:
              example:
                total: 1977
                entries:
                - tenantId: tenantId
                  tenantUnitId: unitId
                  action: LOGIN
                  email: username@example.com
                  fullName: Any User
                  timestamp: 1723035109091
              schema:
                $ref: '#/components/schemas/AccessLogResponse'
          description: OK
      security:
      - ApiKeyAuth:
        - CanViewAuditLog
      summary: Access log
      tags:
      - Audit Log
      x-ibm-ahub-byok: true
  /api/settings/auditlog:
    get:
      description: Retrieve all audit logs using defined query.
      operationId: getAuditLogs
      parameters:
      - description: The offset within the result set
        example: 0
        in: query
        name: offset
        schema:
          type: integer
          format: int32
      - description: The query to filter the results
        example: username@example.com
        in: query
        name: query
        schema:
          type: string
      - description: The size of returned page
        example: 10
        in: query
        name: pageSize
        schema:
          type: integer
          format: int32
      responses:
        '200':
          content:
            application/json:
              example:
                total: 1977
                entries:
                - id: WawO9-p0SJ2ifST460tXYZ
                  action: GET /api/settings
                  message: Aborting request due to Insufficient permissions/access rights for resource method
                  actor:
                    type: USER
                    id: userId
                    name: Any User
                    email: username@example.com
                  timestamp: 1723035109091
                  meta:
                    origin_ip: 10.69.123.42
              schema:
                $ref: '#/components/schemas/AuditLogUiResponse'
          description: OK
      security:
      - ApiKeyAuth:
        - CanViewAuditLog
      summary: Audit log
      tags:
      - Audit Log
      x-ibm-ahub-byok: true
components:
  schemas:
    AuditLogUiResponse:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/AuditLogEntry'
        total:
          type: integer
          format: int64
    LogEntryActor:
      type: object
      properties:
        email:
          type: string
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum:
          - USER
          - API_TOKEN
          - POLICY
      required:
      - id
      - name
      - type
    AccessLogResponse:
      type: object
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/AccessLogEntry'
        total:
          type: integer
          format: int64
    AccessLogEntry:
      type: object
      properties:
        action:
          type: string
          enum:
          - GRANT_TEMP_ACCESS
          - FIRST_LOGIN
          - LOGIN
          - ACCESS
          - FAILED_LOGIN
          - LOGOUT
          - CREATE_API_TOKEN_BY_POLICY
          - IDP_MAPPING
        email:
          type: string
        fullName:
          type: string
        message:
          type: string
        meta:
          type: object
          additionalProperties:
            type: object
        tenantId:
          type: string
        tenantUnitId:
          type: string
        timestamp:
          type: integer
          format: int64
          minimum: 1118583367265
      required:
      - action
      - email
      - fullName
      - tenantId
    AuditLogEntry:
      type: object
      properties:
        action:
          type: string
        actor:
          $ref: '#/components/schemas/LogEntryActor'
        id:
          type: string
        message:
          type: string
        meta:
          type: object
          additionalProperties:
            type: object
        timestamp:
          type: integer
          format: int64
      required:
      - action
      - actor
      - id
      - message
      - meta
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
