openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation SLO Correction Windows API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: SLO Correction Windows
paths:
  /api/slo/correction:
    get:
      operationId: getSloCorrection
      parameters:
      - in: query
        name: sloId
        schema:
          type: array
          description: List of SLO IDs for which Correction Windows needs to be fetched
          example: SLOdCTspkHlS_OzNOATQWgsuw
          items:
            type: string
            description: List of SLO IDs for which Correction Windows needs to be fetched
            example: SLOdCTspkHlS_OzNOATQWgsuw
          uniqueItems: true
      - description: IDs of Correction Configurations to be Excluded from the result
        example: N1Xj6q8QTZu_cfJOGqy4mg
        in: query
        name: excludeCorrectionId
        schema:
          type: array
          items:
            type: string
          uniqueItems: true
      - description: IDs of Correction Configurations to be Included in the result
        example: uvP7Z03pSUuybDT8-WHLDA
        in: query
        name: includeCorrectionId
        schema:
          type: array
          items:
            type: string
          uniqueItems: true
      - in: query
        name: tags
        schema:
          type: array
          items:
            type: string
          uniqueItems: true
      - description: Correction starting timestamp in milliseconds (13-digit)
        example: 1706713140000
        in: query
        name: from
        required: true
        schema:
          type: integer
          format: int64
      - description: Correction ending timestamp in milliseconds (13-digit)
        example: 1706713140000
        in: query
        name: to
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          content:
            application/json:
              example:
                from: 1750125600000
                to: 1750176418243
                correctionWindows:
                - from: 1750165200000
                  to: 1750176418243
                  correctionConfigs:
                  - CpCe85NeQC2xOKXQluC30g
                  sloConfigs:
                  - SLOwfOpxuCJQjauS2IeHDUpAw
                - from: 1750158000000
                  to: 1750176418243
                  correctionConfigs:
                  - p9kWax0uS7K2Who1WegsSg
                  sloConfigs:
                  - SLOffwtrVkfRmCjOZbdv3Ls9g
                - from: 1750150800000
                  to: 1750165200000
                  correctionConfigs:
                  - uvP7Z03pSUuybDT8-WHLDA
                  sloConfigs:
                  - SLOukNGcoooQlev1z7aqONkIg
                - from: 1750125600000
                  to: 1750136400000
                  correctionConfigs:
                  - S8rHrE93Rz2TXScTjBw1eg
                  sloConfigs:
                  - SLO4s-fs-GuT56c3v4KzQKBuQ
                - from: 1750172400000
                  to: 1750176418243
                  correctionConfigs:
                  - 9Uf9TtvVRgOIMR0DkLB2Ng
                  sloConfigs: []
                - from: 1750125600000
                  to: 1750136400000
                  correctionConfigs:
                  - 96MtLg5zRP-lmT4WOUE3Yg
                  sloConfigs:
                  - SLO4s-fs-GuT56c3v4KzQKBuQ
                activeCorrectionConfigIds:
                - S8rHrE93Rz2TXScTjBw1eg
                - uvP7Z03pSUuybDT8-WHLDA
                - CpCe85NeQC2xOKXQluC30g
                - 9Uf9TtvVRgOIMR0DkLB2Ng
                - 96MtLg5zRP-lmT4WOUE3Yg
                - p9kWax0uS7K2Who1WegsSg
                inActiveCorrectionConfigIds:
                - nNMSbRwFQEKoQ1Wj0BCWcg
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Correction'
          description: Fetched SLO Correction Windows Successfully
        '404':
          content:
            application/json:
              example:
                errors:
                - There is No SLO Correction Windows or Error happened while trying to fetch SLO Correction Windows.
              schema:
                type: array
                items:
                  type: string
          description: There is no SLO Correction Window
      security:
      - ApiKeyAuth:
        - Default
      summary: Generate SLO Correction Windows
      tags:
      - SLO Correction Windows
      x-ibm-ahub-byok: true
components:
  schemas:
    CorrectionWindow:
      type: object
      description: List of Correction Windows
      properties:
        correctionConfigs:
          type: array
          description: IDs of the Correction configurations in the Correction Window
          items:
            type: string
            description: IDs of the Correction configurations in the Correction Window
          uniqueItems: true
        from:
          type: string
          format: date-time
          description: Correction Window starting timestamp in milliseconds (13-digit)
        sloConfigs:
          type: array
          description: IDs of the SLO configurations in the Correction Window
          items:
            type: string
            description: IDs of the SLO configurations in the Correction Window
          uniqueItems: true
        to:
          type: string
          format: date-time
          description: Correction Window ending timestamp in milliseconds (13-digit)
    Correction:
      type: object
      properties:
        activeCorrectionConfigIds:
          type: array
          description: IDs of correction configs that are active
          items:
            type: string
            description: IDs of correction configs that are active
          uniqueItems: true
        correctionWindows:
          type: array
          description: List of Correction Windows
          items:
            $ref: '#/components/schemas/CorrectionWindow'
        from:
          type: string
          format: date-time
          description: Correction starting timestamp in milliseconds (13-digit)
        inActiveCorrectionConfigIds:
          type: array
          description: IDs of correction configs that are inactive
          items:
            type: string
            description: IDs of correction configs that are inactive
          uniqueItems: true
        to:
          type: string
          format: date-time
          description: Correction ending timestamp in milliseconds (13-digit)
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
