openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Infrastructure Topology API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Infrastructure Topology
paths:
  /api/infrastructure-monitoring/graph/related-hosts/{snapshotId}:
    get:
      description: Gets the Related Hosts
      operationId: getRelatedHosts
      parameters:
      - description: Snapshot ID running on the host
        in: path
        name: snapshotId
        required: true
        schema:
          type: string
      - description: Size of time window in milliseconds
        in: query
        name: windowSize
        schema:
          type: integer
          format: int64
      - description: Timestamp since Unix Epoch in milliseconds of the end of the time window
        in: query
        name: to
        schema:
          type: integer
          format: int64
      responses:
        '200':
          content:
            application/json:
              example:
              - ZoKkksp277FMLSXIghPKdjZcvfE
              schema:
                type: array
                items:
                  type: string
          description: Returns the snapshot ID of the hosts
      security:
      - ApiKeyAuth:
        - Default
      summary: Related hosts
      tags:
      - Infrastructure Topology
      x-ibm-ahub-byok: true
  /api/infrastructure-monitoring/topology:
    get:
      operationId: getTopology
      parameters:
      - description: Include snapshot data in nodes
        in: query
        name: includeData
        schema:
          type: boolean
      responses:
        '200':
          content:
            application/json:
              example:
                nodes:
                - id: nYlAch5BEuXdyzQ1Q1V3QvW9jpY
                  plugin: kubernetesPod
                  label: openshift-console/downloads-6b8f4d6dfc-zv2tx (pod)
                  entityId:
                    host: ''
                    pluginId: com.instana.forge.infrastructure.paas.kubernetes.derivedentity.pod.KubernetesPod
                    steadyId: b3e550f4-5754-4388-bd44-025ecd9f057e
                edges:
                - source: i5wh2JGMSHMiSt_TH2sHo1rNLaQ
                  destination: k67B5nn-7mpx6i0oCEiIWvP46ko
                  relation: in
              schema:
                $ref: '#/components/schemas/Topology'
          description: OK
      security:
      - ApiKeyAuth:
        - Default
      summary: Gets the infrastructure topology
      tags:
      - Infrastructure Topology
      x-ibm-ahub-byok: true
components:
  schemas:
    GraphNode:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: object
        entityId:
          $ref: '#/components/schemas/EntityId'
        id:
          type: string
          description: GraphNode ID.
        label:
          type: string
          description: Label of the entity
        plugin:
          type: string
          description: Name of the plugin
    Topology:
      type: object
      properties:
        edges:
          type: array
          items:
            $ref: '#/components/schemas/GraphEdge'
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/GraphNode'
    GraphEdge:
      type: object
      properties:
        destination:
          type: string
          description: ID of the outgoing GraphEdge.
        relation:
          type: string
          description: Type of dependency between the source and the destination.
          enum:
          - in
          - is
          - to
          - of
          - connected
          - describes
          - of20
          - to20
          - dummy
          - parent
        source:
          type: string
          description: ID of the incoming GraphEdge.
    EntityId:
      type: object
      properties:
        host:
          type: string
        pluginId:
          type: string
          description: Plugin name
        steadyId:
          type: string
          description: Steady identifier for the entity.
      required:
      - host
      - pluginId
      - steadyId
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
