openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Logging Analyze API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Logging Analyze
paths:
  /api/logging/logs/getLogVolumeUsage:
    get:
      description: 'Returns aggregated log volume usage data for a specified time range and optional grouping tag.

        `fromTs` and `toTs` are required and must define a valid time range (i.e., `fromTs` <= `toTs`).

        Refer to the query parameter description for valid `groupingTag` values.'
      operationId: getLogVolumeUsage
      parameters:
      - description: Start timestamp in seconds. Must be <= `toTs`.
        example: 1682899200
        in: query
        name: fromTs
        required: true
        schema:
          type: integer
          format: int64
      - description: End timestamp in seconds. Must be >= `fromTs`.
        example: 1682899201
        in: query
        name: toTs
        required: true
        schema:
          type: integer
          format: int64
      - description: 'Optional tag to group volume usage by. Valid groupingTag values are:

          `kubernetes_cluster_name`, `kubernetes_daemonset_name`, `kubernetes_namespace_name`,

          `kubernetes_deployment_name`, `host_name`, `zone`.

          '
        example: zone
        in: query
        name: groupingTag
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                Full Data:
                  description: Full Data
                  value:
                    logVolumeUsageItems:
                    - numberOfMonth: 11
                      logVolume: 278141339215
                      retentionPeriods:
                      - retentionDays: 7
                        logVolume: 7253402
                        logVolumeGroups:
                        - label: ''
                          logVolume: 7253402
                        - label: demo-us-cluster
                          logVolume: 0
                        - label: demo-us-eks
                          logVolume: 0
                      - retentionDays: 90
                        logVolume: 13319384221
                        logVolumeGroups:
                        - label: ''
                          logVolume: 13004387032
                        - label: demo-us-cluster
                          logVolume: 265176702
                        - label: demo-us-eks
                          logVolume: 22645862
                        - label: k8s-demo-cluster
                          logVolume: 27142175
                        - label: rci-robotshop
                          logVolume: 32450
                Zero Volume:
                  description: Zero Volume
                  value:
                    logVolumeUsageItems:
                    - numberOfMonth: 1
                      logVolume: 0
                      retentionPeriods: []
                    - numberOfMonth: 2
                      logVolume: 0
                      retentionPeriods: []
                    - numberOfMonth: 3
                      logVolume: 0
                      retentionPeriods: []
              schema:
                $ref: '#/components/schemas/LogVolumeUsageResult'
          description: Successfully retrieved log volume usage data
        '400':
          description: Invalid request (e.g., missing or incorrect time parameters)
        '500':
          description: Unexpected server error
      security:
      - ApiKeyAuth:
        - Default
      summary: Get Log Volume Usage
      tags:
      - Logging Analyze
      x-ibm-ahub-byok: true
components:
  schemas:
    RetentionPeriod:
      type: object
      properties:
        logVolume:
          type: integer
          format: int64
        logVolumeGroups:
          type: array
          items:
            $ref: '#/components/schemas/LogVolumeGroup'
        retentionDays:
          type: integer
          format: int32
          maximum: 90
          minimum: 7
      required:
      - logVolume
    LogVolumeUsageItem:
      type: object
      properties:
        logVolume:
          type: integer
          format: int64
        numberOfMonth:
          type: integer
          format: int32
          maximum: 12
          minimum: 1
        retentionPeriods:
          type: array
          items:
            $ref: '#/components/schemas/RetentionPeriod'
      required:
      - logVolume
      - retentionPeriods
    LogVolumeUsageResult:
      type: object
      properties:
        logVolumeUsageItems:
          type: array
          items:
            $ref: '#/components/schemas/LogVolumeUsageItem'
      required:
      - logVolumeUsageItems
    LogVolumeGroup:
      type: object
      properties:
        label:
          type: string
          maxLength: 256
          minLength: 0
        logVolume:
          type: integer
          format: int64
      required:
      - label
      - logVolume
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
