openapi: 3.2.0
info:
  contact:
    email: support@instana.com
    name: © Instana
    url: http://instana.com
  termsOfService: https://www.instana.com/terms-of-use/
  title: Instana REST API documentation Releases API
  version: 1.307.1417
  x-ibm-ahub-try: true
  x-logo:
    altText: instana logo
    backgroundColor: '#FAFBFC'
    url: header-logo.svg
  description: Searching for answers and best pratices?
servers:
- description: Instana Backend
  url: https://{unit}-{tenant}.instana.io
  variables:
    tenant:
      default: tenant
      description: Customer tenant unit
    unit:
      default: unit
      description: Customer tenant name
- description: Instana Self-Hosted Backend
  url: https://{domain}
  variables:
    domain:
      default: example.com
      description: Customer Self-Hosted domain
tags:
- name: Releases
  description: These APIs can be used to create, update, delete and fetch releases.
paths:
  /api/releases:
    get:
      operationId: getAllReleases
      parameters:
      - in: query
        name: from
        schema:
          type: integer
          format: int64
          description: The timestamp from where one wants to fetch the release markers.
      - in: query
        name: to
        schema:
          type: integer
          format: int64
          description: The timestamp till where one wants to fetch the release markers.
      - in: query
        name: maxResults
        schema:
          type: integer
          format: int32
          description: The maximum number of release markers to be fetched
      responses:
        '200':
          content:
            application/json:
              example:
              - id: Tiu16hLCTniHDtHb_uDV1w
                name: demo-app/main-**
                start: 1709091782000
                lastUpdated: 1709091782533
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReleaseWithMetadata'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureReleases
      summary: Get all releases
      tags:
      - Releases
      x-ibm-ahub-byok: true
      description: Use this API endpoint to retrieve a list of all releases.
    post:
      operationId: postRelease
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Release'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReleaseWithMetadata'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureReleases
      summary: Create release
      tags:
      - Releases
      x-ibm-ahub-byok: true
      description: 'Use this API endpoint to create a release. Release can be created with four different scopes:


        1. Global

        - Release marker is shown on all dashboard pages for Application perspectives, Services, and Endpoints.


        2. Application Perspective

        - Release marker is shown on the dashboard for the Application perspective.


        3. Service

        - Release marker is shown on the dashboards for the Service and all Application perspective dashboards that contain the Service.


        4. Service within an Application Perspective

        - Release Marker will be shown only for the Service within the given Application perspective, but not for other services within the Application perspective.'
  /api/releases/{releaseId}:
    delete:
      operationId: deleteRelease
      parameters:
      - in: path
        name: releaseId
        required: true
        schema:
          type: string
          description: The unique release id which one wants to delete.
          example: XK1e1TE3T9SHKugndn_soQ
      responses:
        default:
          content:
            application/json: {}
          description: default response
      security:
      - ApiKeyAuth:
        - CanConfigureReleases
      summary: Delete release
      tags:
      - Releases
      x-ibm-ahub-byok: true
      description: Use this API endpoint to delete a release.
    get:
      operationId: getRelease
      parameters:
      - description: The unique release id which one wants to retrieve.
        example: XK1e1TF3T9SHKugndn_soQ
        in: path
        name: releaseId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              example:
                id: XK1e1TF3T9SHKugndn_soQ
                name: demo-app/main-**
                start: 1706674621000
                lastUpdated: 1706674621604
              schema:
                $ref: '#/components/schemas/ReleaseWithMetadata'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureReleases
      summary: Get release
      tags:
      - Releases
      x-ibm-ahub-byok: true
      description: Use this API endpoint to retrieve a particular release.
    put:
      operationId: putRelease
      parameters:
      - in: path
        name: releaseId
        required: true
        schema:
          type: string
          description: The unique release id which one wants to update.
          example: XK1e1TQ3T9SHKugndn_soQ
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Release'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReleaseWithMetadata'
          description: OK
      security:
      - ApiKeyAuth:
        - CanConfigureReleases
      summary: Update release
      tags:
      - Releases
      x-ibm-ahub-byok: true
      description: Use this API endpoint to update a release.
components:
  schemas:
    ReleaseScope:
      type: object
      properties:
        applicationId:
          type: string
        applicationName:
          type: string
        serviceId:
          type: string
        serviceName:
          type: string
    ServiceScopeWithMetadata:
      type: object
      description: The list of services where the release can be viewed.
      properties:
        id:
          type: string
          description: 'Unique ID of the Service. Eg: `3feb3dcd206c166ef2b41c707e0cd38d7cd325aa`.'
        name:
          type: string
          description: 'Name of the Service. Eg: `payment`.'
        scopedTo:
          $ref: '#/components/schemas/ServiceScopedToWithMetadata'
      required:
      - id
    ServiceScope:
      type: object
      description: The list of services where the release can be viewed.
      properties:
        name:
          type: string
          description: 'Name of the Service. Eg: `payment`.'
          maxLength: 256
          minLength: 0
        scopedTo:
          $ref: '#/components/schemas/ServiceScopedTo'
      required:
      - name
    ServiceScopedToWithMetadata:
      type: object
      description: The release marker would be present in the service but not for other services within the Application perspective.
      properties:
        applications:
          type: array
          description: 'The list of application perspectives where the service is present. '
          items:
            $ref: '#/components/schemas/ApplicationScopeWithMetadata'
          maxItems: 10
          minItems: 1
      required:
      - applications
    Release:
      type: object
      properties:
        applications:
          type: array
          description: The list of application perspectives where the release can be viewed.
          items:
            $ref: '#/components/schemas/ApplicationScope'
          maxItems: 10
          minItems: 0
        name:
          type: string
          description: 'The name of the release. For example: `frontend/release-2000`.'
          maxLength: 256
          minLength: 0
        services:
          type: array
          description: The list of services where the release can be viewed.
          items:
            $ref: '#/components/schemas/ServiceScope'
          maxItems: 10
          minItems: 0
        start:
          type: integer
          format: int64
          description: 'The timestamp for when the release is created. The time measured is in milliseconds. For example: `1742349976000` is `Wednesday, 19 March 2025 02:06:16 GMT`.'
          minimum: 1
      required:
      - name
      - start
    ReleaseWithMetadata:
      type: object
      properties:
        applications:
          type: array
          description: The list of application perspectives where the release can be viewed.
          items:
            $ref: '#/components/schemas/ApplicationScopeWithMetadata'
          maxItems: 10
          minItems: 0
        id:
          type: string
          description: 'A unique id for a release. For example: `l1wgr3DsQkGLf8u18JiGsg`.'
          maxLength: 64
          minLength: 0
        lastUpdated:
          type: integer
          format: int64
          description: 'The timestamp for when the same release is updated. The time measured is in milliseconds. For example: `1742369990000` is `Wednesday, 19 March 2025 07:39:50 GMT`.'
          minimum: 1
        name:
          type: string
          description: 'The name of the release. For example: `frontend/release-2000`.'
          maxLength: 256
          minLength: 0
        scopes:
          type: array
          items:
            $ref: '#/components/schemas/ReleaseScope'
          writeOnly: true
        services:
          type: array
          description: The list of services where the release can be viewed.
          items:
            $ref: '#/components/schemas/ServiceScopeWithMetadata'
          maxItems: 10
          minItems: 0
        start:
          type: integer
          format: int64
          description: 'The timestamp for when the release is created. The time measured is in milliseconds. For example: `1742349976000` is `Wednesday, 19 March 2025 02:06:16 GMT`.'
          minimum: 1
      required:
      - id
      - name
    ApplicationScopeWithMetadata:
      type: object
      description: The list of application perspectives where the release can be viewed.
      properties:
        id:
          type: string
          description: 'Unique ID of the Application Perspective. Eg: `Av62RoIKQv-A3n6DbMQh9g`.'
        name:
          type: string
          description: 'Name of the Application Perspective. Eg: `app1`.'
      required:
      - id
    ServiceScopedTo:
      type: object
      description: 'The list of application perspectives where the service is present. '
      properties:
        applications:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationScope'
          maxItems: 10
          minItems: 1
      required:
      - applications
    ApplicationScope:
      type: object
      description: The list of application perspectives where the release can be viewed.
      properties:
        name:
          type: string
          description: 'Name of the Application Perspective. Eg: `app1`.'
          maxLength: 256
          minLength: 0
      required:
      - name
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: authorization
      type: apiKey
      description: "## Example\n\n```bash\ncurl --request GET \\\n  --url https://test-instana.instana.io/api/application-monitoring/catalog/metrics \\\n  --header 'authorization: apiToken xxxxxxxxxxxxxxxx'\n```\n"
x-tagGroups:
- name: Websites & Mobile Apps
  tags:
  - Website Metrics
  - Website Catalog
  - Website Analyze
  - Website Configuration
  - Mobile App Metrics
  - Mobile App Catalog
  - Mobile App Analyze
  - Mobile App Configuration
  - End User Monitoring
- name: Applications
  tags:
  - Application Metrics
  - Application Resources
  - Application Catalog
  - Application Analyze
  - Application Settings
  - Application Topology
  - Application Alert Configuration
  - Global Application Alert Configuration
- name: Infrastructure
  tags:
  - Infrastructure Analyze
  - Infrastructure Metrics
  - Infrastructure Resources
  - Infrastructure Catalog
  - Infrastructure Topology
- name: Logging
  tags:
  - Logging Analyze
- name: Synthetic Monitoring
  tags:
  - Synthetic Catalog
  - Synthetic Metrics
  - Synthetic Settings
  - Synthetic Test Playback Results
  - Synthetic Alert Configuration
- name: Logs
  tags:
  - Log Alert Configuration
- name: Events
  tags:
  - Events
  - Event Settings
- name: Automation
  tags:
  - Action Catalog
  - Action History
  - Policies
- name: Service Levels
  tags:
  - SLI Settings
  - SLI Report
  - Apdex Settings
  - Apdex Report
  - Service Levels Objective(SLO) Configurations
  - Service Levels Objective(SLO) Report
  - Service Levels Alert Configuration
  - SLO Correction Configurations
  - SLO Correction Windows
- name: AI Management
  tags:
  - AI Management
- name: Settings
  tags:
  - Custom Dashboards
  - User
  - Groups
  - Teams
  - Roles
  - Audit Log
  - API Token
  - Maintenance Configuration
  - Synthetic Calls
  - Session Settings
  - Automation Settings
  - Authentication
- name: Open Beta Features
  tags:
  - Infrastructure Analyze
- name: Closed Beta Features
  tags:
  - Infrastructure Alert Configuration
- name: Instana
  tags:
  - Releases
  - Host Agent
  - Health
  - Usage
